export const SCHEDULE_TITLE_NOT_EXIST = 'SCHEDULE_TITLE_NOT_EXIST';
export const SCHEDULE_TITLE_INVALID_TYPE = 'SCHEDULE_TITLE_INVALID_TYPE';

export const SCHEDULE_SOURCE_NOT_EXIST = 'SCHEDULE_SOURCE_NOT_EXIST';
export const SCHEDULE_SOURCE_INVALID_TYPE = 'SCHEDULE_SOURCE_INVALID_TYPE';
export const SCHEDULE_SOURCE_INVALID_VAL = 'SCHEDULE_SOURCE_INVALID_VAL';

export const SCHEDULE_RECTIME_NOT_EXIST = 'SCHEDULE_RECTIME_NOT_EXIST';
export const SCHEDULE_RECTIME_INVALID_VAL = 'SCHEDULE_RECTIME_INVALID_VAL';
export const SCHEDULE_RECTIME_MIN_LESS = 'SCHEDULE_RECTIME_MIN_LESS';
export const SCHEDULE_RECTIME_MAX_OVER = 'SCHEDULE_RECTIME_MAX_OVER';

export const SCHEDULE_STARTTIME_NOT_EXIST = 'SCHEDULE_STARTTIME_NOT_EXIST';

export const SCHEDULE_STARTTIME_DAYOFWEEK_INVALID_TYPE = 'SCHEDULE_STARTTIME_DAYOFWEEK_INVALID_TYPE';
export const SCHEDULE_STARTTIME_DAYOFWEEK_INVALID_VAL = 'SCHEDULE_STARTTIME_DAYOFWEEK_INVALID_VAL';
export const SCHEDULE_STARTTIME_DAYOFWEEK_MIN_LESS = 'SCHEDULE_STARTTIME_DAYOFWEEK_MIN_LESS';
export const SCHEDULE_STARTTIME_DAYOFWEEK_MAX_OVER = 'SCHEDULE_STARTTIME_DAYOFWEEK_MAX_OVER';

export const SCHEDULE_STARTTIME_MONTH_NOT_EXIST = 'SCHEDULE_STARTTIME_MONTH_NOT_EXIST';
export const SCHEDULE_STARTTIME_MONTH_INVALID_TYPE = 'SCHEDULE_STARTTIME_MONTH_INVALID_TYPE';
export const SCHEDULE_STARTTIME_MONTH_INVALID_VAL = 'SCHEDULE_STARTTIME_MONTH_INVALID_VAL';
export const SCHEDULE_STARTTIME_MONTH_MIN_LESS = 'SCHEDULE_STARTTIME_MONTH_MIN_LESS';
export const SCHEDULE_STARTTIME_MONTH_MAX_OVER = 'SCHEDULE_STARTTIME_MONTH_MAX_OVER';

export const SCHEDULE_STARTTIME_DATE_NOT_EXIST = 'SCHEDULE_STARTTIME_DATE_NOT_EXIST';
export const SCHEDULE_STARTTIME_DATE_INVALID_TYPE = 'SCHEDULE_STARTTIME_DATE_INVALID_TYPE';
export const SCHEDULE_STARTTIME_DATE_INVALID_VAL = 'SCHEDULE_STARTTIME_DATE_INVALID_VAL';
export const SCHEDULE_STARTTIME_DATE_MIN_LESS = 'SCHEDULE_STARTTIME_DATE_MIN_LESS';
export const SCHEDULE_STARTTIME_DATE_MAX_OVER = 'SCHEDULE_STARTTIME_DATE_MAX_OVER';

export const SCHEDULE_STARTTIME_HOURS_NOT_EXIST = 'SCHEDULE_STARTTIME_HOURS_NOT_EXIST';
export const SCHEDULE_STARTTIME_HOURS_INVALID_VAL = 'SCHEDULE_STARTTIME_HOURS_INVALID_VAL';
export const SCHEDULE_STARTTIME_HOURS_MIN_LESS = 'SCHEDULE_STARTTIME_HOURS_MIN_LESS';
export const SCHEDULE_STARTTIME_HOURS_MAX_OVER = 'SCHEDULE_STARTTIME_HOURS_MAX_OVER';

export const SCHEDULE_STARTTIME_MINUTES_NOT_EXIST = 'SCHEDULE_STARTTIME_MINUTES_NOT_EXIST';
export const SCHEDULE_STARTTIME_MINUTES_INVALID_VAL = 'SCHEDULE_STARTTIME_MINUTES_INVALID_VAL';
export const SCHEDULE_STARTTIME_MINUTES_MIN_LESS = 'SCHEDULE_STARTTIME_MINUTES_MIN_LESS';
export const SCHEDULE_STARTTIME_MINUTES_MAX_OVER = 'SCHEDULE_STARTTIME_MINUTES_MAX_OVER';

export const SCHEDULE_STARTTIME_SECONDS_NOT_EXIST = 'SCHEDULE_STARTTIME_SECONDS_NOT_EXIST';
export const SCHEDULE_STARTTIME_SECONDS_INVALID_VAL = 'SCHEDULE_STARTTIME_SECONDS_INVALID_VAL';
export const SCHEDULE_STARTTIME_SECONDS_MIN_LESS = 'SCHEDULE_STARTTIME_SECONDS_MIN_LESS';
export const SCHEDULE_STARTTIME_SECONDS_MAX_OVER = 'SCHEDULE_STARTTIME_SECONDS_MAX_OVER';
